### ISSUE TITLE
Pypi package renaming

### ISSUE THREAD

**Issue by Forden** [SFTtech/aiomatrix#14]
Hi! I'm developing client library for matrix in Python and wanted to publish it on PyPi as aiomatrix but found your [library](https://pypi.org/project/aiomatrix/). It looks abandoned, so I thought it's okay to ask if you could rename your PyPi package.
Could you please change your library name to aiomatrix-py or something like that?

**Comment by TheJJ** [comment]
Hi! I'm sorry but we may have plans in the future to revive the project, so I can't fully abandon it yet. But surely you'll find another great name for your project :) good luck!
